import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Two sidebars, one per navbar entry (see the navbar in docusaurus.config.ts). The folder name is the
 * audience, and that is the whole convention:
 *
 * - `userGuide` — for people who use the extension from SQL: `user-guide/` (what it adds, how to
 *   install and load it, and the functions it registers). No Rust, no build steps.
 * - `development` — for people working on this repository: `development/` (quick start, project
 *   structure, writing and testing functions, build and release, community registration).
 *
 * Both are `autogenerated`, so adding a page means dropping it into the right folder; the order inside
 * comes from each page's `sidebar_position`.
 *
 * 两个侧边栏，对应顶栏两项。目录名就是受众，这就是全部约定：
 *
 * - `userGuide` —— 用 SQL 调用这个扩展的人：`user-guide/`（它加了什么、怎么装与加载、注册了哪些函数），
 *   不出现 Rust 与构建步骤。
 * - `development` —— 改这个仓库的人：`development/`（快速开始、目录结构、写函数与测试、构建与发版、
 *   社区扩展注册）。
 *
 * 两者都是 `autogenerated`：新增页面只要放进对应目录，目录内部的顺序由各页的 `sidebar_position` 决定。
 */
const sidebars: SidebarsConfig = {
  userGuide: [{type: 'autogenerated', dirName: 'user-guide'}],
  development: [{type: 'autogenerated', dirName: 'development'}],
};

export default sidebars;
